/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.kirunews.rpha.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.kirunews.rpha.struts.form.AdvancedSearchForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-21-2009
 * 
 * XDoclet definition:
 * @struts.action path="/advancedSearch" name="advancedSearchForm" input="/form/advancedSearch.jsp" scope="request" validate="true"
 */
public class AdvancedSearchAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AdvancedSearchForm advancedSearchForm = (AdvancedSearchForm) form;// TODO Auto-generated method stub
		return mapping.getInputForward();
	}
}