/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.kirunews.rpha.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.kirunews.rpha.struts.form.CommonSearchForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-07-2008
 * 
 * XDoclet definition:
 * @struts.action path="/commonSearch" name="commonSearchForm" input="/form/commonSearch.jsp" scope="request" validate="true"
 */
public class CommonSearchAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CommonSearchForm commonSearchForm = (CommonSearchForm) form;// TODO Auto-generated method stub
		return mapping.getInputForward();
	}
}