/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.kirunews.rpha.struts.action;

import java.io.FileNotFoundException;
import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.kirunews.rpha.model.ListIncipits;
import com.kirunews.rpha.struts.form.IncipitForm;
import com.kirunews.rpha.util.Logging;

/** 
 * MyEclipse Struts
 * Creation date: 12-06-2007
 * 
 * XDoclet definition:
 * @struts.action path="/incipit" name="incipitForm" input="/form/incipit.jsp" scope="request" validate="true"
 */
public class IncipitAction extends Action {
	/*
	 * Generated Methods
	 */
	private static Logger logger = Logging.getLogger();

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm actionForm,
			HttpServletRequest request, HttpServletResponse response) {
		IncipitForm form = (IncipitForm) actionForm;
		try {
			ListIncipits list = new ListIncipits();
			form.setIncipits(list.list(form.getInc()));
			logger.error("get the incipit list");
		} catch(FileNotFoundException e) {
			logger.error(e.getMessage());
			e.printStackTrace();
		} catch(IOException e) {
			logger.error(e.getMessage());
			e.printStackTrace();
		}
		
		return mapping.getInputForward();
	}
}