/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.kirunews.rpha.struts.action;

import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.kirunews.rpha.model.ListBooks;
import com.kirunews.rpha.struts.form.ListBooksForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-18-2007
 * 
 * XDoclet definition:
 * @struts.action path="/listBooks" name="listBooksForm" input="/form/listBooks.jsp" scope="request" validate="true"
 */
public class ListBooksAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm actionForm,
			HttpServletRequest request, HttpServletResponse response) {
		ListBooksForm form = (ListBooksForm) actionForm;
		//ActionMessages errors = new ActionMessages();
		try {
			ListBooks lister = new ListBooks();
			if(form.getType() == null) {
				form.setHtml(lister.simpleList().replaceAll("BASE_PATH", request.getContextPath()));
			} else {
				form.setHtml(lister.typeList(form.getType()).replaceAll("BASE_PATH", request.getContextPath()));
			}
		} catch(IOException e) {
			e.printStackTrace();
			//errors.add("io", new ActionMessage("listbook.io", e.getMessage()));
		}
		return mapping.getInputForward();
	}
}