/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.kirunews.rpha.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.kirunews.rpha.struts.form.NewBookForm;
import com.kirunews.rpha.util.Logging;

/** 
 * MyEclipse Struts
 * Creation date: 12-28-2007
 * 
 * XDoclet definition:
 * @struts.action path="/newBook" name="newBookForm" input="/form/newBook.jsp" scope="request" validate="true"
 */
public class NewBookAction extends Action {
	private static Logger logger = Logging.getLogger();

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm bookForm,
			HttpServletRequest request, HttpServletResponse response) {
		logger.info("New book");
		NewBookForm form = (NewBookForm) bookForm;
		if(form.getId() == null)
			form.setId("");
		return mapping.getInputForward();
	}
}