/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.kirunews.rpha.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.kirunews.rpha.struts.form.NewVersionForm;
import com.kirunews.rpha.util.Logging;

/** 
 * MyEclipse Struts
 * Creation date: 12-28-2007
 * 
 * XDoclet definition:
 * @struts.action path="/newVersion" name="newVersionForm" input="/form/newVersion.jsp" scope="request" validate="true"
 */
public class NewVersionAction extends Action {
	private static Logger logger = Logging.getLogger();

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm versionForm,
			HttpServletRequest request, HttpServletResponse response) {
		logger.info("new version");
		NewVersionForm form = (NewVersionForm) versionForm;
		form.setSource("");

		return mapping.getInputForward();
	}
}