/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.kirunews.rpha.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-07-2008
 * 
 * XDoclet definition:
 * @struts.form name="commonSearchForm"
 */
public class CommonSearchForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** rhymeScheme property */
	private String rhymeScheme;

	/** gonicStructure property */
	private String gonicStructure;

	/** specialRhymes property */
	private String specialRhymes;

	/** rhetoricalProcedures property */
	private String rhetoricalProcedures;

	/** metricalScheme property */
	private String metricalScheme;

	/** tornadas property */
	private String tornadas;

	/** rhymes property */
	private String rhymes;

	/** internalGenre property */
	private String internalGenre;

	/** refrain property */
	private String refrain;

	/** incipit property */
	private String incipit;

	/** extresnalGenre property */
	private String externalGenre;

	/** numberOfStanzas property */
	private String numberOfStanzas;

	/** source property */
	private String source;

	/** genre property */
	private String genre;

	/** author property */
	private String author;

	/** reference property */
	private String reference;
	
	private String[] database;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the rhymeScheme.
	 * @return String
	 */
	public String getRhymeScheme() {
		return rhymeScheme;
	}

	/** 
	 * Set the rhymeScheme.
	 * @param rhymeScheme The rhymeScheme to set
	 */
	public void setRhymeScheme(String rhymeScheme) {
		this.rhymeScheme = rhymeScheme;
	}

	/** 
	 * Returns the gonicStructure.
	 * @return String
	 */
	public String getGonicStructure() {
		return gonicStructure;
	}

	/** 
	 * Set the gonicStructure.
	 * @param gonicStructure The gonicStructure to set
	 */
	public void setGonicStructure(String gonicStructure) {
		this.gonicStructure = gonicStructure;
	}

	/** 
	 * Returns the specialRhymes.
	 * @return String
	 */
	public String getSpecialRhymes() {
		return specialRhymes;
	}

	/** 
	 * Set the specialRhymes.
	 * @param specialRhymes The specialRhymes to set
	 */
	public void setSpecialRhymes(String specialRhymes) {
		this.specialRhymes = specialRhymes;
	}

	/** 
	 * Returns the rhetoricalProcedures.
	 * @return String
	 */
	public String getRhetoricalProcedures() {
		return rhetoricalProcedures;
	}

	/** 
	 * Set the rhetoricalProcedures.
	 * @param rhetoricalProcedures The rhetoricalProcedures to set
	 */
	public void setRhetoricalProcedures(String rhetoricalProcedures) {
		this.rhetoricalProcedures = rhetoricalProcedures;
	}

	/** 
	 * Returns the metricalScheme.
	 * @return String
	 */
	public String getMetricalScheme() {
		return metricalScheme;
	}

	/** 
	 * Set the metricalScheme.
	 * @param metricalScheme The metricalScheme to set
	 */
	public void setMetricalScheme(String metricalScheme) {
		this.metricalScheme = metricalScheme;
	}

	/** 
	 * Returns the tornadas.
	 * @return String
	 */
	public String getTornadas() {
		return tornadas;
	}

	/** 
	 * Set the tornadas.
	 * @param tornadas The tornadas to set
	 */
	public void setTornadas(String tornadas) {
		this.tornadas = tornadas;
	}

	/** 
	 * Returns the rhymes.
	 * @return String
	 */
	public String getRhymes() {
		return rhymes;
	}

	/** 
	 * Set the rhymes.
	 * @param rhymes The rhymes to set
	 */
	public void setRhymes(String rhymes) {
		this.rhymes = rhymes;
	}

	/** 
	 * Returns the internalGenre.
	 * @return String
	 */
	public String getInternalGenre() {
		return internalGenre;
	}

	/** 
	 * Set the internalGenre.
	 * @param internalGenre The internalGenre to set
	 */
	public void setInternalGenre(String internalGenre) {
		this.internalGenre = internalGenre;
	}

	/** 
	 * Returns the refrain.
	 * @return String
	 */
	public String getRefrain() {
		return refrain;
	}

	/** 
	 * Set the refrain.
	 * @param refrain The refrain to set
	 */
	public void setRefrain(String refrain) {
		this.refrain = refrain;
	}

	/** 
	 * Returns the incipit.
	 * @return String
	 */
	public String getIncipit() {
		return incipit;
	}

	/** 
	 * Set the incipit.
	 * @param incipit The incipit to set
	 */
	public void setIncipit(String incipit) {
		this.incipit = incipit;
	}

	/** 
	 * Returns the externalGenre.
	 * @return String
	 */
	public String getExternalGenre() {
		return externalGenre;
	}

	/** 
	 * Set the externalGenre.
	 * @param externalGenre The externalGenre to set
	 */
	public void setExternalGenre(String externalGenre) {
		this.externalGenre = externalGenre;
	}

	/** 
	 * Returns the numberOfStanzas.
	 * @return String
	 */
	public String getNumberOfStanzas() {
		return numberOfStanzas;
	}

	/** 
	 * Set the numberOfStanzas.
	 * @param numberOfStanzas The numberOfStanzas to set
	 */
	public void setNumberOfStanzas(String numberOfStanzas) {
		this.numberOfStanzas = numberOfStanzas;
	}

	/** 
	 * Returns the source.
	 * @return String
	 */
	public String getSource() {
		return source;
	}

	/** 
	 * Set the source.
	 * @param source The source to set
	 */
	public void setSource(String source) {
		this.source = source;
	}

	/** 
	 * Returns the genre.
	 * @return String
	 */
	public String getGenre() {
		return genre;
	}

	/** 
	 * Set the genre.
	 * @param genre The genre to set
	 */
	public void setGenre(String genre) {
		this.genre = genre;
	}

	/** 
	 * Returns the author.
	 * @return String
	 */
	public String getAuthor() {
		return author;
	}

	/** 
	 * Set the author.
	 * @param author The author to set
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/** 
	 * Returns the reference.
	 * @return String
	 */
	public String getReference() {
		return reference;
	}

	/** 
	 * Set the reference.
	 * @param reference The reference to set
	 */
	public void setReference(String reference) {
		this.reference = reference;
	}

	public String[] getDatabase() {
		return database;
	}

	public void setDatabase(String[] database) {
		this.database = database;
	}
}